import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(6):
        arm.rigify_colors.add()

    arm.rigify_colors[0].name = "Root"
    arm.rigify_colors[0].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[0].normal = Color((0.4353, 0.1843, 0.4157))
    arm.rigify_colors[0].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[0].standard_colors_lock = True
    arm.rigify_colors[1].name = "IK"
    arm.rigify_colors[1].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[1].normal = Color((0.6039, 0.0000, 0.0000))
    arm.rigify_colors[1].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[1].standard_colors_lock = True
    arm.rigify_colors[2].name = "Special"
    arm.rigify_colors[2].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[2].normal = Color((0.9569, 0.7882, 0.0471))
    arm.rigify_colors[2].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[2].standard_colors_lock = True
    arm.rigify_colors[3].name = "Tweak"
    arm.rigify_colors[3].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[3].normal = Color((0.0392, 0.2118, 0.5804))
    arm.rigify_colors[3].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[3].standard_colors_lock = True
    arm.rigify_colors[4].name = "FK"
    arm.rigify_colors[4].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[4].normal = Color((0.1176, 0.5686, 0.0353))
    arm.rigify_colors[4].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[4].standard_colors_lock = True
    arm.rigify_colors[5].name = "Extra"
    arm.rigify_colors[5].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[5].normal = Color((0.9686, 0.2510, 0.0941))
    arm.rigify_colors[5].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[5].standard_colors_lock = True

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Face', ui_row=1, color_set_id=5)
    add_bone_collection('Face (Primary)', ui_row=2, color_set_id=2)
    add_bone_collection('Face (Secondary)', ui_row=2, color_set_id=3)
    add_bone_collection('Torso', ui_row=3, color_set_id=3)
    add_bone_collection('Torso (Tweak)', ui_row=4, color_set_id=4)
    add_bone_collection('Fingers', ui_row=5, color_set_id=6)
    add_bone_collection('Fingers (Detail)', ui_row=6, color_set_id=5)
    add_bone_collection('Arm.L (IK)', ui_row=7, color_set_id=2)
    add_bone_collection('Arm.L (FK)', ui_row=8, color_set_id=5)
    add_bone_collection('Arm.L (Tweak)', ui_row=9, color_set_id=4)
    add_bone_collection('Arm.R (IK)', ui_row=7, color_set_id=2)
    add_bone_collection('Arm.R (FK)', ui_row=8, color_set_id=5)
    add_bone_collection('Arm.R (Tweak)', ui_row=9, color_set_id=4)
    add_bone_collection('Leg.L (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.L (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.L (Tweak)', ui_row=12, color_set_id=4)
    add_bone_collection('Leg.R (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.R (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.R (Tweak)', ui_row=12, color_set_id=4)
    add_bone_collection('Root', ui_row=15, color_set_id=1)
    add_bone_collection('hair', ui_row=13)

    bones = {}

    bone = arm.edit_bones.new('char_root')
    bone.head = 0.0000, 0.0000, 0.0000
    bone.tail = 0.0000, 0.2160, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bones['char_root'] = bone.name
    bone = arm.edit_bones.new('spine')
    bone.head = 0.0000, -0.0299, 0.9263
    bone.tail = 0.0000, -0.0299, 1.0232
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['char_root']]
    bones['spine'] = bone.name
    bone = arm.edit_bones.new('spine.001')
    bone.head = 0.0000, -0.0299, 1.0232
    bone.tail = 0.0000, -0.0155, 1.1754
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine']]
    bones['spine.001'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head = 0.1027, -0.0299, 0.9263
    bone.tail = 0.1376, -0.0250, 0.4894
    bone.roll = -0.0868
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head = -0.1027, -0.0299, 0.9263
    bone.tail = -0.1376, -0.0250, 0.4894
    bone.roll = 0.0868
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('toolBone')
    bone.head = -0.7032, 0.0000, 1.0000
    bone.tail = -0.7032, 0.0000, 0.4773
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['toolBone'] = bone.name
    bone = arm.edit_bones.new('spine.003')
    bone.head = 0.0000, -0.0155, 1.1754
    bone.tail = 0.0000, 0.0328, 1.4406
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.001']]
    bones['spine.003'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head = 0.1376, -0.0250, 0.4894
    bone.tail = 0.1673, 0.0225, 0.1176
    bone.roll = -0.0712
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head = -0.1376, -0.0250, 0.4894
    bone.tail = -0.1673, 0.0225, 0.1176
    bone.roll = 0.0712
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('neck.001')
    bone.head = 0.0000, 0.0328, 1.4406
    bone.tail = 0.0000, 0.0102, 1.5558
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['neck.001'] = bone.name
    bone = arm.edit_bones.new('shoulder.L')
    bone.head = 0.0295, -0.0049, 1.3862
    bone.tail = 0.1442, 0.0177, 1.3632
    bone.roll = 0.1025
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('shoulder.R')
    bone.head = -0.0295, -0.0049, 1.3862
    bone.tail = -0.1442, 0.0177, 1.3632
    bone.roll = -0.1025
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['shoulder.R'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head = 0.1673, 0.0225, 0.1176
    bone.tail = 0.1673, -0.0698, 0.0491
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head = -0.1673, 0.0225, 0.1176
    bone.tail = -0.1673, -0.0698, 0.0491
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head = 0.0000, 0.0102, 1.5558
    bone.tail = 0.0000, 0.0102, 1.8186
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['neck.001']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head = 0.1518, 0.0231, 1.3167
    bone.tail = 0.3008, 0.0321, 1.1470
    bone.roll = 2.3535
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head = -0.1518, 0.0231, 1.3167
    bone.tail = -0.3008, 0.0321, 1.1470
    bone.roll = -2.3535
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.R']]
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head = 0.1673, -0.0698, 0.0491
    bone.tail = 0.1673, -0.1279, 0.0491
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('heel.02.L')
    bone.head = 0.1345, 0.0697, 0.0000
    bone.tail = 0.2036, 0.0697, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['heel.02.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head = -0.1673, -0.0698, 0.0491
    bone.tail = -0.1673, -0.1279, 0.0491
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('heel.02.R')
    bone.head = -0.1345, 0.0697, 0.0000
    bone.tail = -0.2036, 0.0697, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['heel.02.R'] = bone.name
    bone = arm.edit_bones.new('bone.01.L')
    bone.head = 0.0993, 0.1322, 1.7032
    bone.tail = 0.1114, 0.1537, 1.5169
    bone.roll = 3.0769
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['bone.01.L'] = bone.name
    bone = arm.edit_bones.new('bone.01.R')
    bone.head = -0.0993, 0.1322, 1.7032
    bone.tail = -0.1114, 0.1537, 1.5169
    bone.roll = -3.0769
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['bone.01.R'] = bone.name
    bone = arm.edit_bones.new('DEF-eye_up.L')
    bone.head = 0.0584, -0.0962, 1.6747
    bone.tail = 0.0584, -0.1374, 1.6915
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['DEF-eye_up.L'] = bone.name
    bone = arm.edit_bones.new('DEF-eye_down.L')
    bone.head = 0.0584, -0.0962, 1.6747
    bone.tail = 0.0584, -0.1328, 1.6524
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['DEF-eye_down.L'] = bone.name
    bone = arm.edit_bones.new('DEF-eye.L')
    bone.head = 0.0584, -0.0962, 1.6747
    bone.tail = 0.0584, -0.1390, 1.6747
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['DEF-eye.L'] = bone.name
    bone = arm.edit_bones.new('eye_C')
    bone.head = 0.0000, -0.2807, 1.6736
    bone.tail = 0.0000, -0.3253, 1.6736
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye_C'] = bone.name
    bone = arm.edit_bones.new('eye_up_C.L')
    bone.head = 0.0584, -0.1598, 1.6918
    bone.tail = 0.0584, -0.1811, 1.6918
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye_up_C.L'] = bone.name
    bone = arm.edit_bones.new('eye_down_C.L')
    bone.head = 0.0584, -0.1598, 1.6458
    bone.tail = 0.0584, -0.1811, 1.6458
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye_down_C.L'] = bone.name
    bone = arm.edit_bones.new('DEF-eye_up.R')
    bone.head = -0.0584, -0.0962, 1.6747
    bone.tail = -0.0584, -0.1374, 1.6915
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['DEF-eye_up.R'] = bone.name
    bone = arm.edit_bones.new('DEF-eye_down.R')
    bone.head = -0.0584, -0.0962, 1.6747
    bone.tail = -0.0584, -0.1328, 1.6524
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['DEF-eye_down.R'] = bone.name
    bone = arm.edit_bones.new('DEF-eye.R')
    bone.head = -0.0584, -0.0962, 1.6747
    bone.tail = -0.0584, -0.1390, 1.6747
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['DEF-eye.R'] = bone.name
    bone = arm.edit_bones.new('eye_up_C.R')
    bone.head = -0.0584, -0.1598, 1.6918
    bone.tail = -0.0584, -0.1811, 1.6918
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye_up_C.R'] = bone.name
    bone = arm.edit_bones.new('eye_down_C.R')
    bone.head = -0.0584, -0.1598, 1.6458
    bone.tail = -0.0584, -0.1811, 1.6458
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye_down_C.R'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head = 0.3008, 0.0321, 1.1470
    bone.tail = 0.4380, 0.0029, 0.9889
    bone.roll = 2.3576
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head = -0.3008, 0.0321, 1.1470
    bone.tail = -0.4380, 0.0029, 0.9889
    bone.roll = -2.3576
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('tip.L')
    bone.head = 0.1673, -0.1503, 0.0000
    bone.tail = 0.1673, -0.1768, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.L']]
    bones['tip.L'] = bone.name
    bone = arm.edit_bones.new('tip.R')
    bone.head = -0.1673, -0.1503, 0.0000
    bone.tail = -0.1673, -0.1768, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.R']]
    bones['tip.R'] = bone.name
    bone = arm.edit_bones.new('bone.02.L')
    bone.head = 0.1114, 0.1537, 1.5169
    bone.tail = 0.1235, 0.1753, 1.3305
    bone.roll = 6.2185
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.01.L']]
    bones['bone.02.L'] = bone.name
    bone = arm.edit_bones.new('bone.02.R')
    bone.head = -0.1114, 0.1537, 1.5169
    bone.tail = -0.1235, 0.1753, 1.3305
    bone.roll = -6.2185
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.01.R']]
    bones['bone.02.R'] = bone.name
    bone = arm.edit_bones.new('eye_C.L')
    bone.head = 0.0584, -0.2807, 1.6747
    bone.tail = 0.0584, -0.3253, 1.6747
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye_C']]
    bones['eye_C.L'] = bone.name
    bone = arm.edit_bones.new('eye_C.R')
    bone.head = -0.0584, -0.2807, 1.6747
    bone.tail = -0.0584, -0.3253, 1.6747
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye_C']]
    bones['eye_C.R'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head = 0.4380, 0.0029, 0.9889
    bone.tail = 0.4704, -0.0043, 0.9411
    bone.roll = 2.5797
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('hand.R')
    bone.head = -0.4380, 0.0029, 0.9889
    bone.tail = -0.4704, -0.0043, 0.9411
    bone.roll = -2.5797
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['hand.R'] = bone.name
    bone = arm.edit_bones.new('bone.03.L')
    bone.head = 0.1235, 0.1753, 1.3305
    bone.tail = 0.1355, 0.1968, 1.1442
    bone.roll = 6.2185
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.02.L']]
    bones['bone.03.L'] = bone.name
    bone = arm.edit_bones.new('bone.03.R')
    bone.head = -0.1235, 0.1753, 1.3305
    bone.tail = -0.1355, 0.1968, 1.1442
    bone.roll = -6.2185
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.02.R']]
    bones['bone.03.R'] = bone.name
    bone = arm.edit_bones.new('palm.01.L')
    bone.head = 0.4575, -0.0328, 0.9763
    bone.tail = 0.4992, -0.0513, 0.9260
    bone.roll = -2.1880
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.01.L'] = bone.name
    bone = arm.edit_bones.new('palm.02.L')
    bone.head = 0.4633, -0.0137, 0.9745
    bone.tail = 0.5051, -0.0260, 0.9259
    bone.roll = -2.2463
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.02.L'] = bone.name
    bone = arm.edit_bones.new('palm.03.L')
    bone.head = 0.4631, 0.0044, 0.9743
    bone.tail = 0.5010, 0.0021, 0.9269
    bone.roll = -2.2759
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.03.L'] = bone.name
    bone = arm.edit_bones.new('palm.04.L')
    bone.head = 0.4531, 0.0236, 0.9687
    bone.tail = 0.4882, 0.0270, 0.9270
    bone.roll = -2.3031
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.04.L'] = bone.name
    bone = arm.edit_bones.new('palm.01.R')
    bone.head = -0.4575, -0.0328, 0.9763
    bone.tail = -0.4992, -0.0513, 0.9260
    bone.roll = 2.1880
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.01.R'] = bone.name
    bone = arm.edit_bones.new('palm.02.R')
    bone.head = -0.4633, -0.0137, 0.9745
    bone.tail = -0.5051, -0.0260, 0.9259
    bone.roll = 2.2463
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.02.R'] = bone.name
    bone = arm.edit_bones.new('palm.03.R')
    bone.head = -0.4631, 0.0044, 0.9743
    bone.tail = -0.5010, 0.0021, 0.9269
    bone.roll = 2.2759
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.03.R'] = bone.name
    bone = arm.edit_bones.new('palm.04.R')
    bone.head = -0.4531, 0.0236, 0.9687
    bone.tail = -0.4882, 0.0270, 0.9270
    bone.roll = 2.3031
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.04.R'] = bone.name
    bone = arm.edit_bones.new('f_index.01.L')
    bone.head = 0.4992, -0.0513, 0.9260
    bone.tail = 0.5202, -0.0599, 0.8785
    bone.roll = -1.8314
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.L']]
    bones['f_index.01.L'] = bone.name
    bone = arm.edit_bones.new('thumb.01.L')
    bone.head = 0.4381, -0.0301, 0.9762
    bone.tail = 0.4399, -0.0661, 0.9401
    bone.roll = 0.3936
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.L']]
    bones['thumb.01.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.L')
    bone.head = 0.5051, -0.0260, 0.9259
    bone.tail = 0.5258, -0.0325, 0.8717
    bone.roll = -1.8427
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.02.L']]
    bones['f_middle.01.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.L')
    bone.head = 0.5010, 0.0021, 0.9269
    bone.tail = 0.5221, -0.0015, 0.8774
    bone.roll = -2.0091
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.03.L']]
    bones['f_ring.01.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.L')
    bone.head = 0.4882, 0.0270, 0.9270
    bone.tail = 0.5080, 0.0264, 0.8911
    bone.roll = -2.2307
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.04.L']]
    bones['f_pinky.01.L'] = bone.name
    bone = arm.edit_bones.new('f_index.01.R')
    bone.head = -0.4992, -0.0513, 0.9260
    bone.tail = -0.5202, -0.0599, 0.8785
    bone.roll = 1.8314
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.R']]
    bones['f_index.01.R'] = bone.name
    bone = arm.edit_bones.new('thumb.01.R')
    bone.head = -0.4381, -0.0301, 0.9762
    bone.tail = -0.4399, -0.0661, 0.9401
    bone.roll = -0.3936
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.R']]
    bones['thumb.01.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.R')
    bone.head = -0.5051, -0.0260, 0.9259
    bone.tail = -0.5258, -0.0325, 0.8717
    bone.roll = 1.8427
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.02.R']]
    bones['f_middle.01.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.R')
    bone.head = -0.5010, 0.0021, 0.9269
    bone.tail = -0.5221, -0.0015, 0.8774
    bone.roll = 2.0091
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.03.R']]
    bones['f_ring.01.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.R')
    bone.head = -0.4882, 0.0270, 0.9270
    bone.tail = -0.5080, 0.0264, 0.8911
    bone.roll = 2.2307
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.04.R']]
    bones['f_pinky.01.R'] = bone.name
    bone = arm.edit_bones.new('f_index.02.L')
    bone.head = 0.5202, -0.0599, 0.8785
    bone.tail = 0.5274, -0.0637, 0.8492
    bone.roll = -1.6313
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.01.L']]
    bones['f_index.02.L'] = bone.name
    bone = arm.edit_bones.new('thumb.02.L')
    bone.head = 0.4399, -0.0661, 0.9401
    bone.tail = 0.4507, -0.0864, 0.9051
    bone.roll = -0.0460
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.01.L']]
    bones['thumb.02.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.L')
    bone.head = 0.5258, -0.0325, 0.8717
    bone.tail = 0.5341, -0.0347, 0.8375
    bone.roll = -1.7081
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.01.L']]
    bones['f_middle.02.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.L')
    bone.head = 0.5221, -0.0015, 0.8774
    bone.tail = 0.5294, -0.0033, 0.8483
    bone.roll = -1.8433
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.01.L']]
    bones['f_ring.02.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.L')
    bone.head = 0.5080, 0.0264, 0.8911
    bone.tail = 0.5172, 0.0262, 0.8683
    bone.roll = -2.1087
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.L']]
    bones['f_pinky.02.L'] = bone.name
    bone = arm.edit_bones.new('f_index.02.R')
    bone.head = -0.5202, -0.0599, 0.8785
    bone.tail = -0.5274, -0.0637, 0.8492
    bone.roll = 1.6313
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.01.R']]
    bones['f_index.02.R'] = bone.name
    bone = arm.edit_bones.new('thumb.02.R')
    bone.head = -0.4399, -0.0661, 0.9401
    bone.tail = -0.4507, -0.0864, 0.9051
    bone.roll = 0.0460
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.01.R']]
    bones['thumb.02.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.R')
    bone.head = -0.5258, -0.0325, 0.8717
    bone.tail = -0.5341, -0.0347, 0.8375
    bone.roll = 1.7081
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.01.R']]
    bones['f_middle.02.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.R')
    bone.head = -0.5221, -0.0015, 0.8774
    bone.tail = -0.5294, -0.0033, 0.8483
    bone.roll = 1.8433
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.01.R']]
    bones['f_ring.02.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.R')
    bone.head = -0.5080, 0.0264, 0.8911
    bone.tail = -0.5172, 0.0262, 0.8683
    bone.roll = 2.1087
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.R']]
    bones['f_pinky.02.R'] = bone.name
    bone = arm.edit_bones.new('f_index.03.L')
    bone.head = 0.5274, -0.0637, 0.8492
    bone.tail = 0.5316, -0.0661, 0.8251
    bone.roll = -1.5759
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.02.L']]
    bones['f_index.03.L'] = bone.name
    bone = arm.edit_bones.new('thumb.03.L')
    bone.head = 0.4507, -0.0864, 0.9051
    bone.tail = 0.4621, -0.0960, 0.8773
    bone.roll = -0.1548
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.02.L']]
    bones['thumb.03.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.L')
    bone.head = 0.5341, -0.0347, 0.8375
    bone.tail = 0.5378, -0.0363, 0.8117
    bone.roll = -1.6131
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.02.L']]
    bones['f_middle.03.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.L')
    bone.head = 0.5294, -0.0033, 0.8483
    bone.tail = 0.5340, -0.0047, 0.8247
    bone.roll = -1.7919
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.02.L']]
    bones['f_ring.03.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.L')
    bone.head = 0.5172, 0.0262, 0.8683
    bone.tail = 0.5228, 0.0262, 0.8454
    bone.roll = -1.9706
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.L']]
    bones['f_pinky.03.L'] = bone.name
    bone = arm.edit_bones.new('f_index.03.R')
    bone.head = -0.5274, -0.0637, 0.8492
    bone.tail = -0.5316, -0.0661, 0.8251
    bone.roll = 1.5759
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.02.R']]
    bones['f_index.03.R'] = bone.name
    bone = arm.edit_bones.new('thumb.03.R')
    bone.head = -0.4507, -0.0864, 0.9051
    bone.tail = -0.4621, -0.0960, 0.8773
    bone.roll = 0.1548
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.02.R']]
    bones['thumb.03.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.R')
    bone.head = -0.5341, -0.0347, 0.8375
    bone.tail = -0.5378, -0.0363, 0.8117
    bone.roll = 1.6131
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.02.R']]
    bones['f_middle.03.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.R')
    bone.head = -0.5294, -0.0033, 0.8483
    bone.tail = -0.5340, -0.0047, 0.8247
    bone.roll = 1.7919
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.02.R']]
    bones['f_ring.03.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.R')
    bone.head = -0.5172, 0.0262, 0.8683
    bone.tail = -0.5228, 0.0262, 0.8454
    bone.roll = 1.9706
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.R']]
    bones['f_pinky.03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['char_root']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Face', 'Face (Primary)', 'Face (Secondary)', 'Torso', 'Fingers', 'Arm.L (IK)', 'Arm.R (IK)', 'Leg.L (IK)', 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'diamond'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine']]
    pbone.rigify_type = 'game.spines.basic_spine'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.pivot_pos = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.rigify_type = 'game.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.L (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.L (Tweak)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.rigify_type = 'game.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.R (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.R (Tweak)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toolBone']]
    pbone.rigify_type = 'game.basic.pivot'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    try:
        pbone.rigify_parameters.make_extra_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_parent_switch = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.register_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.register_parent_tags = 'injected'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['neck.001']]
    pbone.rigify_type = 'game.spines.super_head'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.connect_chain = True
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.R']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.rigify_type = 'game.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.L (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.L (FK)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.rigify_type = 'game.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.R (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.R (FK)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['heel.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['heel.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bone.01.L']]
    pbone.rigify_type = 'game.basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['bone.01.R']]
    pbone.rigify_type = 'game.basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['DEF-eye_up.L']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_ROTATION')
    con.name = 'Copy Rotation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'DEF-eye.L'
    con.use_x = True
    con.use_y = False
    con.use_z = False
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.euler_order = 'AUTO'
    con.mix_mode = 'REPLACE'
    con.use_offset = False
    con = pbone.constraints.new('TRANSFORM')
    con.name = 'Transformation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'eye_up_C.L'
    con.map_from = 'LOCATION'
    con.map_to = 'ROTATION'
    con.map_to_x_from = 'Z'
    con.map_to_y_from = 'Y'
    con.map_to_z_from = 'X'
    con.use_motion_extrapolate = False
    con.from_rotation_mode = 'AUTO'
    con.to_euler_order = 'AUTO'
    con.from_min_x = 0.0
    con.from_min_y = 0.0
    con.from_min_z = -0.03999999910593033
    con.from_max_x = 0.0
    con.from_max_y = 0.0
    con.from_max_z = 0.03999999910593033
    con.to_min_x = 0.0
    con.to_min_y = 0.0
    con.to_min_z = 0.0
    con.to_max_x = 0.0
    con.to_max_y = 0.0
    con.to_max_z = 0.0
    con.mix_mode = 'ADD'
    con.from_min_x_rot = 0.0
    con.from_min_y_rot = 0.0
    con.from_min_z_rot = 0.0
    con.from_max_x_rot = 0.0
    con.from_max_y_rot = 0.0
    con.from_max_z_rot = 0.0
    con.to_min_x_rot = -0.8726646304130554
    con.to_min_y_rot = 0.0
    con.to_min_z_rot = 0.0
    con.to_max_x_rot = 0.8726646304130554
    con.to_max_y_rot = 0.0
    con.to_max_z_rot = 0.0
    con.mix_mode_rot = 'ADD'
    con.from_min_x_scale = 1.0
    con.from_min_y_scale = 1.0
    con.from_min_z_scale = 1.0
    con.from_max_x_scale = 1.0
    con.from_max_y_scale = 1.0
    con.from_max_z_scale = 1.0
    con.to_min_x_scale = 1.0
    con.to_min_y_scale = 1.0
    con.to_min_z_scale = 1.0
    con.to_max_x_scale = 1.0
    con.to_max_y_scale = 1.0
    con.to_max_z_scale = 1.0
    con.mix_mode_scale = 'REPLACE'
    con = pbone.constraints.new('LIMIT_ROTATION')
    con.name = 'Limit Rotation'
    con.owner_space = 'LOCAL'
    con.use_limit_x = True
    con.use_limit_y = False
    con.use_limit_z = False
    con.min_x = -0.8761552572250366
    con.min_y = 0.0
    con.min_z = 0.0
    con.max_x = 0.10821040719747543
    con.max_y = 0.0
    con.max_z = 0.0
    con.euler_order = 'AUTO'
    con.use_transform_limit = False
    con.use_legacy_behavior = False
    pbone = obj.pose.bones[bones['DEF-eye_down.L']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_ROTATION')
    con.name = 'Copy Rotation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'DEF-eye.L'
    con.use_x = True
    con.use_y = False
    con.use_z = False
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.euler_order = 'AUTO'
    con.mix_mode = 'REPLACE'
    con.use_offset = False
    con = pbone.constraints.new('TRANSFORM')
    con.name = 'Transformation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'eye_down_C.L'
    con.map_from = 'LOCATION'
    con.map_to = 'ROTATION'
    con.map_to_x_from = 'Z'
    con.map_to_y_from = 'Y'
    con.map_to_z_from = 'X'
    con.use_motion_extrapolate = False
    con.from_rotation_mode = 'AUTO'
    con.to_euler_order = 'AUTO'
    con.from_min_x = 0.0
    con.from_min_y = 0.0
    con.from_min_z = -0.03999999910593033
    con.from_max_x = 0.0
    con.from_max_y = 0.0
    con.from_max_z = 0.03999999910593033
    con.to_min_x = 0.0
    con.to_min_y = 0.0
    con.to_min_z = 0.0
    con.to_max_x = 0.0
    con.to_max_y = 0.0
    con.to_max_z = 0.0
    con.mix_mode = 'ADD'
    con.from_min_x_rot = 0.0
    con.from_min_y_rot = 0.0
    con.from_min_z_rot = 0.0
    con.from_max_x_rot = 0.0
    con.from_max_y_rot = 0.0
    con.from_max_z_rot = 0.0
    con.to_min_x_rot = -0.8726646304130554
    con.to_min_y_rot = 0.0
    con.to_min_z_rot = 0.0
    con.to_max_x_rot = 0.8726646304130554
    con.to_max_y_rot = 0.0
    con.to_max_z_rot = 0.0
    con.mix_mode_rot = 'ADD'
    con.from_min_x_scale = 1.0
    con.from_min_y_scale = 1.0
    con.from_min_z_scale = 1.0
    con.from_max_x_scale = 1.0
    con.from_max_y_scale = 1.0
    con.from_max_z_scale = 1.0
    con.to_min_x_scale = 1.0
    con.to_min_y_scale = 1.0
    con.to_min_z_scale = 1.0
    con.to_max_x_scale = 1.0
    con.to_max_y_scale = 1.0
    con.to_max_z_scale = 1.0
    con.mix_mode_scale = 'REPLACE'
    con = pbone.constraints.new('LIMIT_ROTATION')
    con.name = 'Limit Rotation'
    con.owner_space = 'LOCAL'
    con.use_limit_x = True
    con.use_limit_y = False
    con.use_limit_z = False
    con.min_x = -0.10297447443008423
    con.min_y = 0.0
    con.min_z = 0.0
    con.max_x = 0.8726646304130554
    con.max_y = 0.0
    con.max_z = 0.0
    con.euler_order = 'AUTO'
    con.use_transform_limit = False
    con.use_legacy_behavior = False
    pbone = obj.pose.bones[bones['DEF-eye.L']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('DAMPED_TRACK')
    con.name = 'Damped Track'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'eye_C.L'
    con.track_axis = 'TRACK_Y'
    pbone = obj.pose.bones[bones['eye_C']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'diamond'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_up_C.L']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (True, True, False)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'circle'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('LIMIT_LOCATION')
    con.name = 'Limit Location'
    con.owner_space = 'LOCAL'
    con.use_min_x = False
    con.use_min_y = False
    con.use_min_z = True
    con.use_max_x = False
    con.use_max_y = False
    con.use_max_z = True
    con.min_x = 0.0
    con.min_y = 0.0
    con.min_z = -0.04111799970269203
    con.max_x = 0.0
    con.max_y = 0.0
    con.max_z = 0.006668000016361475
    con.use_transform_limit = False
    pbone = obj.pose.bones[bones['eye_down_C.L']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (True, True, False)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'circle'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('LIMIT_LOCATION')
    con.name = 'Limit Location'
    con.owner_space = 'LOCAL'
    con.use_min_x = False
    con.use_min_y = False
    con.use_min_z = True
    con.use_max_x = False
    con.use_max_y = False
    con.use_max_z = True
    con.min_x = 0.0
    con.min_y = 0.0
    con.min_z = -0.004912000149488449
    con.max_x = 0.0
    con.max_y = 0.0
    con.max_z = 0.043331995606422424
    con.use_transform_limit = False
    pbone = obj.pose.bones[bones['DEF-eye_up.R']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_ROTATION')
    con.name = 'Copy Rotation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'DEF-eye.R'
    con.use_x = True
    con.use_y = False
    con.use_z = False
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.euler_order = 'AUTO'
    con.mix_mode = 'REPLACE'
    con.use_offset = False
    con = pbone.constraints.new('TRANSFORM')
    con.name = 'Transformation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'eye_up_C.R'
    con.map_from = 'LOCATION'
    con.map_to = 'ROTATION'
    con.map_to_x_from = 'Z'
    con.map_to_y_from = 'Y'
    con.map_to_z_from = 'X'
    con.use_motion_extrapolate = False
    con.from_rotation_mode = 'AUTO'
    con.to_euler_order = 'AUTO'
    con.from_min_x = -0.0
    con.from_min_y = 0.0
    con.from_min_z = -0.03999999910593033
    con.from_max_x = 0.0
    con.from_max_y = 0.0
    con.from_max_z = 0.03999999910593033
    con.to_min_x = 0.0
    con.to_min_y = 0.0
    con.to_min_z = 0.0
    con.to_max_x = 0.0
    con.to_max_y = 0.0
    con.to_max_z = 0.0
    con.mix_mode = 'ADD'
    con.from_min_x_rot = 0.0
    con.from_min_y_rot = 0.0
    con.from_min_z_rot = 0.0
    con.from_max_x_rot = 0.0
    con.from_max_y_rot = 0.0
    con.from_max_z_rot = 0.0
    con.to_min_x_rot = -0.8726646304130554
    con.to_min_y_rot = 0.0
    con.to_min_z_rot = 0.0
    con.to_max_x_rot = 0.8726646304130554
    con.to_max_y_rot = 0.0
    con.to_max_z_rot = 0.0
    con.mix_mode_rot = 'ADD'
    con.from_min_x_scale = 1.0
    con.from_min_y_scale = 1.0
    con.from_min_z_scale = 1.0
    con.from_max_x_scale = 1.0
    con.from_max_y_scale = 1.0
    con.from_max_z_scale = 1.0
    con.to_min_x_scale = 1.0
    con.to_min_y_scale = 1.0
    con.to_min_z_scale = 1.0
    con.to_max_x_scale = 1.0
    con.to_max_y_scale = 1.0
    con.to_max_z_scale = 1.0
    con.mix_mode_scale = 'REPLACE'
    con = pbone.constraints.new('LIMIT_ROTATION')
    con.name = 'Limit Rotation'
    con.owner_space = 'LOCAL'
    con.use_limit_x = True
    con.use_limit_y = False
    con.use_limit_z = False
    con.min_x = -0.8761552572250366
    con.min_y = 0.0
    con.min_z = 0.0
    con.max_x = 0.10821040719747543
    con.max_y = 0.0
    con.max_z = 0.0
    con.euler_order = 'AUTO'
    con.use_transform_limit = False
    con.use_legacy_behavior = False
    pbone = obj.pose.bones[bones['DEF-eye_down.R']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_ROTATION')
    con.name = 'Copy Rotation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'DEF-eye.R'
    con.use_x = True
    con.use_y = False
    con.use_z = False
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.euler_order = 'AUTO'
    con.mix_mode = 'REPLACE'
    con.use_offset = False
    con = pbone.constraints.new('TRANSFORM')
    con.name = 'Transformation'
    con.target = obj
    con.owner_space = 'LOCAL'
    con.target_space = 'LOCAL'
    con.subtarget = 'eye_down_C.R'
    con.map_from = 'LOCATION'
    con.map_to = 'ROTATION'
    con.map_to_x_from = 'Z'
    con.map_to_y_from = 'Y'
    con.map_to_z_from = 'X'
    con.use_motion_extrapolate = False
    con.from_rotation_mode = 'AUTO'
    con.to_euler_order = 'AUTO'
    con.from_min_x = -0.0
    con.from_min_y = 0.0
    con.from_min_z = -0.03999999910593033
    con.from_max_x = 0.0
    con.from_max_y = 0.0
    con.from_max_z = 0.03999999910593033
    con.to_min_x = 0.0
    con.to_min_y = 0.0
    con.to_min_z = 0.0
    con.to_max_x = 0.0
    con.to_max_y = 0.0
    con.to_max_z = 0.0
    con.mix_mode = 'ADD'
    con.from_min_x_rot = 0.0
    con.from_min_y_rot = 0.0
    con.from_min_z_rot = 0.0
    con.from_max_x_rot = 0.0
    con.from_max_y_rot = 0.0
    con.from_max_z_rot = 0.0
    con.to_min_x_rot = -0.8726646304130554
    con.to_min_y_rot = 0.0
    con.to_min_z_rot = 0.0
    con.to_max_x_rot = 0.8726646304130554
    con.to_max_y_rot = 0.0
    con.to_max_z_rot = 0.0
    con.mix_mode_rot = 'ADD'
    con.from_min_x_scale = 1.0
    con.from_min_y_scale = 1.0
    con.from_min_z_scale = 1.0
    con.from_max_x_scale = 1.0
    con.from_max_y_scale = 1.0
    con.from_max_z_scale = 1.0
    con.to_min_x_scale = 1.0
    con.to_min_y_scale = 1.0
    con.to_min_z_scale = 1.0
    con.to_max_x_scale = 1.0
    con.to_max_y_scale = 1.0
    con.to_max_z_scale = 1.0
    con.mix_mode_scale = 'REPLACE'
    con = pbone.constraints.new('LIMIT_ROTATION')
    con.name = 'Limit Rotation'
    con.owner_space = 'LOCAL'
    con.use_limit_x = True
    con.use_limit_y = False
    con.use_limit_z = False
    con.min_x = -0.10297447443008423
    con.min_y = 0.0
    con.min_z = 0.0
    con.max_x = 0.8726646304130554
    con.max_y = 0.0
    con.max_z = 0.0
    con.euler_order = 'AUTO'
    con.use_transform_limit = False
    con.use_legacy_behavior = False
    pbone = obj.pose.bones[bones['DEF-eye.R']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('DAMPED_TRACK')
    con.name = 'Damped Track'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'eye_C.R'
    con.track_axis = 'TRACK_Y'
    pbone = obj.pose.bones[bones['eye_up_C.R']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (True, True, False)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'circle'
    except AttributeError:
        pass
    con = pbone.constraints.new('LIMIT_LOCATION')
    con.name = 'Limit Location'
    con.owner_space = 'LOCAL'
    con.use_min_x = False
    con.use_min_y = False
    con.use_min_z = True
    con.use_max_x = False
    con.use_max_y = False
    con.use_max_z = True
    con.min_x = -0.0
    con.min_y = 0.0
    con.min_z = -0.04111799970269203
    con.max_x = 0.0
    con.max_y = 0.0
    con.max_z = 0.006668000016361475
    con.use_transform_limit = False
    pbone = obj.pose.bones[bones['eye_down_C.R']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (True, True, False)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'circle'
    except AttributeError:
        pass
    con = pbone.constraints.new('LIMIT_LOCATION')
    con.name = 'Limit Location'
    con.owner_space = 'LOCAL'
    con.use_min_x = False
    con.use_min_y = False
    con.use_min_z = True
    con.use_max_x = False
    con.use_max_y = False
    con.use_max_z = True
    con.min_x = -0.0
    con.min_y = 0.0
    con.min_z = -0.004912000149488449
    con.max_x = 0.0
    con.max_y = 0.0
    con.max_z = 0.043331995606422424
    con.use_transform_limit = False
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tip.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tip.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bone.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['bone.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['eye_C.L']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'circle'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_C.R']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'circle'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hand.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bone.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['bone.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['palm.01.L']]
    pbone.rigify_type = 'game.limbs.super_palm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.04.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.01.R']]
    pbone.rigify_type = 'game.limbs.super_palm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.04.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
