import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('arm', ui_row=2)
    add_bone_collection('feathers', ui_row=1)
    add_bone_collection('feathers (tweaks)', ui_row=1)
    add_bone_collection('Root', ui_row=5)

    bones = {}

    bone = arm.edit_bones.new('Bone.083')
    bone.head = 5.4531, 0.1048, 0.0326
    bone.tail = 3.8242, 0.0515, 0.1055
    bone.roll = -1.5182
    bone.use_connect = False
    bones['Bone.083'] = bone.name
    bone = arm.edit_bones.new('Bone')
    bone.head = 3.3812, -0.0000, 0.0268
    bone.tail = 0.3588, -0.8563, 0.0060
    bone.roll = -1.5777
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.083']]
    bones['Bone'] = bone.name
    bone = arm.edit_bones.new('Bone.001')
    bone.head = 0.3588, -0.8563, 0.0060
    bone.tail = -3.1043, 0.0000, -0.0147
    bone.roll = -1.5769
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone']]
    bones['Bone.001'] = bone.name
    bone = arm.edit_bones.new('Bone.006')
    bone.head = 3.3812, -0.0000, 0.0268
    bone.tail = 2.6386, -0.2104, 0.0217
    bone.roll = -1.5777
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone']]
    bones['Bone.006'] = bone.name
    bone = arm.edit_bones.new('Bone.002')
    bone.head = -3.1043, 0.0000, -0.0147
    bone.tail = -4.0675, -0.3265, -0.0147
    bone.roll = -1.5706
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.001']]
    bones['Bone.002'] = bone.name
    bone = arm.edit_bones.new('Bone.005')
    bone.head = -3.2104, 0.1388, -0.0147
    bone.tail = -3.8739, 0.3606, -0.0147
    bone.roll = -1.5733
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.001']]
    bones['Bone.005'] = bone.name
    bone = arm.edit_bones.new('Bone.007')
    bone.head = 0.3588, -0.8563, 0.0060
    bone.tail = -0.4203, -0.6636, 0.0014
    bone.roll = -1.5769
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.001']]
    bones['Bone.007'] = bone.name
    bone = arm.edit_bones.new('Bone.020')
    bone.head = 0.7575, -1.3420, -0.0147
    bone.tail = 0.7526, -2.2624, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.006']]
    bone.bbone_segments = 5
    bones['Bone.020'] = bone.name
    bone = arm.edit_bones.new('Bone.021')
    bone.head = 1.5151, -1.1310, -0.0147
    bone.tail = 1.5102, -2.0514, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.006']]
    bone.bbone_segments = 5
    bones['Bone.021'] = bone.name
    bone = arm.edit_bones.new('Bone.022')
    bone.head = 2.1614, -0.9547, -0.0147
    bone.tail = 2.1565, -1.8752, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.006']]
    bone.bbone_segments = 5
    bones['Bone.022'] = bone.name
    bone = arm.edit_bones.new('Bone.023')
    bone.head = 2.7605, -0.6814, -0.0147
    bone.tail = 2.7556, -1.6019, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.006']]
    bone.bbone_segments = 5
    bones['Bone.023'] = bone.name
    bone = arm.edit_bones.new('Bone.024')
    bone.head = 3.4245, -0.4039, -0.0147
    bone.tail = 3.4196, -1.3244, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.006']]
    bone.bbone_segments = 5
    bones['Bone.024'] = bone.name
    bone = arm.edit_bones.new('Bone.003')
    bone.head = -4.1194, -0.3422, -0.0147
    bone.tail = -4.7777, -0.5445, -0.0147
    bone.roll = -1.5706
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.002']]
    bones['Bone.003'] = bone.name
    bone = arm.edit_bones.new('Bone.009')
    bone.head = -3.1043, 0.0000, -0.0147
    bone.tail = -3.5073, -0.1366, -0.0147
    bone.roll = -1.5706
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.002']]
    bones['Bone.009'] = bone.name
    bone = arm.edit_bones.new('Bone.008')
    bone.head = -2.8840, -0.2497, -0.0147
    bone.tail = -2.8889, -1.1701, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.007']]
    bone.bbone_segments = 5
    bones['Bone.008'] = bone.name
    bone = arm.edit_bones.new('Bone.016')
    bone.head = -2.4507, -0.4994, -0.0147
    bone.tail = -2.4556, -1.4198, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.007']]
    bone.bbone_segments = 5
    bones['Bone.016'] = bone.name
    bone = arm.edit_bones.new('Bone.017')
    bone.head = -1.5641, -0.8805, -0.0147
    bone.tail = -1.5690, -1.8009, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.007']]
    bone.bbone_segments = 5
    bones['Bone.017'] = bone.name
    bone = arm.edit_bones.new('Bone.018')
    bone.head = -0.8088, -1.1167, -0.0147
    bone.tail = -0.8137, -2.0372, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.007']]
    bone.bbone_segments = 5
    bones['Bone.018'] = bone.name
    bone = arm.edit_bones.new('Bone.019')
    bone.head = -0.0018, -1.2415, -0.0147
    bone.tail = -0.0067, -2.1620, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.007']]
    bone.bbone_segments = 5
    bones['Bone.019'] = bone.name
    bone = arm.edit_bones.new('Bone.053')
    bone.head = 0.7526, -2.2624, -0.0147
    bone.tail = 0.7477, -3.1829, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.020']]
    bone.bbone_segments = 5
    bones['Bone.053'] = bone.name
    bone = arm.edit_bones.new('Bone.055')
    bone.head = 1.5102, -2.0514, -0.0147
    bone.tail = 1.5053, -2.9719, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.021']]
    bone.bbone_segments = 5
    bones['Bone.055'] = bone.name
    bone = arm.edit_bones.new('Bone.057')
    bone.head = 2.1565, -1.8752, -0.0147
    bone.tail = 2.1516, -2.7956, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.022']]
    bone.bbone_segments = 5
    bones['Bone.057'] = bone.name
    bone = arm.edit_bones.new('Bone.059')
    bone.head = 2.7556, -1.6019, -0.0147
    bone.tail = 2.7507, -2.5223, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.023']]
    bone.bbone_segments = 5
    bones['Bone.059'] = bone.name
    bone = arm.edit_bones.new('Bone.061')
    bone.head = 3.4196, -1.3244, -0.0147
    bone.tail = 3.4147, -2.2448, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.024']]
    bone.bbone_segments = 5
    bones['Bone.061'] = bone.name
    bone = arm.edit_bones.new('Bone.004')
    bone.head = -4.8495, -0.5583, -0.0147
    bone.tail = -5.3801, -0.7216, -0.0147
    bone.roll = -1.5706
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.003']]
    bones['Bone.004'] = bone.name
    bone = arm.edit_bones.new('Bone.010')
    bone.head = -4.1194, -0.3422, -0.0147
    bone.tail = -4.3695, -0.4190, -0.0147
    bone.roll = -1.5706
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.003']]
    bones['Bone.010'] = bone.name
    bone = arm.edit_bones.new('Bone.025')
    bone.head = -3.4054, -0.4774, -0.0147
    bone.tail = -3.4095, -1.2485, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.009']]
    bone.bbone_segments = 5
    bones['Bone.025'] = bone.name
    bone = arm.edit_bones.new('Bone.026')
    bone.head = -3.7506, -0.6316, -0.0147
    bone.tail = -3.7541, -1.2892, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.009']]
    bone.bbone_segments = 5
    bones['Bone.026'] = bone.name
    bone = arm.edit_bones.new('Bone.043')
    bone.head = -2.8889, -1.1701, -0.0147
    bone.tail = -2.8938, -2.0906, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.008']]
    bone.bbone_segments = 5
    bones['Bone.043'] = bone.name
    bone = arm.edit_bones.new('Bone.045')
    bone.head = -2.4556, -1.4198, -0.0147
    bone.tail = -2.4605, -2.3403, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.016']]
    bone.bbone_segments = 5
    bones['Bone.045'] = bone.name
    bone = arm.edit_bones.new('Bone.047')
    bone.head = -1.5690, -1.8009, -0.0147
    bone.tail = -1.5739, -2.7214, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.017']]
    bone.bbone_segments = 5
    bones['Bone.047'] = bone.name
    bone = arm.edit_bones.new('Bone.049')
    bone.head = -0.8137, -2.0372, -0.0147
    bone.tail = -0.8186, -2.9576, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.018']]
    bone.bbone_segments = 5
    bones['Bone.049'] = bone.name
    bone = arm.edit_bones.new('Bone.051')
    bone.head = -0.0067, -2.1620, -0.0147
    bone.tail = -0.0116, -3.0825, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.019']]
    bone.bbone_segments = 5
    bones['Bone.051'] = bone.name
    bone = arm.edit_bones.new('Bone.054')
    bone.head = 0.7477, -3.1829, -0.0147
    bone.tail = 0.7428, -4.1033, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.053']]
    bone.bbone_segments = 5
    bones['Bone.054'] = bone.name
    bone = arm.edit_bones.new('Bone.056')
    bone.head = 1.5053, -2.9719, -0.0147
    bone.tail = 1.5004, -3.8923, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.055']]
    bone.bbone_segments = 5
    bones['Bone.056'] = bone.name
    bone = arm.edit_bones.new('Bone.058')
    bone.head = 2.1516, -2.7956, -0.0147
    bone.tail = 2.1467, -3.7161, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.057']]
    bone.bbone_segments = 5
    bones['Bone.058'] = bone.name
    bone = arm.edit_bones.new('Bone.060')
    bone.head = 2.7507, -2.5223, -0.0147
    bone.tail = 2.7458, -3.4428, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.059']]
    bone.bbone_segments = 5
    bones['Bone.060'] = bone.name
    bone = arm.edit_bones.new('Bone.062')
    bone.head = 3.4147, -2.2448, -0.0147
    bone.tail = 3.4098, -3.1653, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.061']]
    bone.bbone_segments = 5
    bones['Bone.062'] = bone.name
    bone = arm.edit_bones.new('Bone.011')
    bone.head = -4.8495, -0.5583, -0.0147
    bone.tail = -5.1213, -0.6420, -0.0147
    bone.roll = -1.5706
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.004']]
    bones['Bone.011'] = bone.name
    bone = arm.edit_bones.new('Bone.027')
    bone.head = -4.1545, -0.6242, -0.0147
    bone.tail = -4.1576, -1.2079, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.010']]
    bone.bbone_segments = 5
    bones['Bone.027'] = bone.name
    bone = arm.edit_bones.new('Bone.028')
    bone.head = -4.5511, -0.7124, -0.0147
    bone.tail = -4.5535, -1.1734, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.010']]
    bone.bbone_segments = 5
    bones['Bone.028'] = bone.name
    bone = arm.edit_bones.new('Bone.039')
    bone.head = -3.4095, -1.2485, -0.0147
    bone.tail = -3.4136, -2.0196, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.025']]
    bone.bbone_segments = 5
    bones['Bone.039'] = bone.name
    bone = arm.edit_bones.new('Bone.041')
    bone.head = -3.7541, -1.2892, -0.0147
    bone.tail = -3.7576, -1.9469, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.026']]
    bone.bbone_segments = 5
    bones['Bone.041'] = bone.name
    bone = arm.edit_bones.new('Bone.044')
    bone.head = -2.8938, -2.0906, -0.0147
    bone.tail = -2.8987, -3.0111, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.043']]
    bone.bbone_segments = 5
    bones['Bone.044'] = bone.name
    bone = arm.edit_bones.new('Bone.046')
    bone.head = -2.4605, -2.3403, -0.0147
    bone.tail = -2.4654, -3.2608, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.045']]
    bone.bbone_segments = 5
    bones['Bone.046'] = bone.name
    bone = arm.edit_bones.new('Bone.048')
    bone.head = -1.5739, -2.7214, -0.0147
    bone.tail = -1.5788, -3.6419, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.047']]
    bone.bbone_segments = 5
    bones['Bone.048'] = bone.name
    bone = arm.edit_bones.new('Bone.050')
    bone.head = -0.8186, -2.9576, -0.0147
    bone.tail = -0.8235, -3.8781, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.049']]
    bone.bbone_segments = 5
    bones['Bone.050'] = bone.name
    bone = arm.edit_bones.new('Bone.052')
    bone.head = -0.0116, -3.0825, -0.0147
    bone.tail = -0.0165, -4.0029, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.051']]
    bone.bbone_segments = 5
    bones['Bone.052'] = bone.name
    bone = arm.edit_bones.new('Bone.029')
    bone.head = -4.9109, -0.7858, -0.0147
    bone.tail = -4.9128, -1.1414, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.011']]
    bone.bbone_segments = 5
    bones['Bone.029'] = bone.name
    bone = arm.edit_bones.new('Bone.030')
    bone.head = -5.2341, -0.8593, -0.0147
    bone.tail = -5.2355, -1.1233, -0.0147
    bone.roll = -1.5649
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bone.011']]
    bone.bbone_segments = 5
    bones['Bone.030'] = bone.name
    bone = arm.edit_bones.new('Bone.035')
    bone.head = -4.1576, -1.2079, -0.0147
    bone.tail = -4.1607, -1.7915, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.027']]
    bone.bbone_segments = 5
    bones['Bone.035'] = bone.name
    bone = arm.edit_bones.new('Bone.037')
    bone.head = -4.5535, -1.1734, -0.0147
    bone.tail = -4.5560, -1.6344, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.028']]
    bone.bbone_segments = 5
    bones['Bone.037'] = bone.name
    bone = arm.edit_bones.new('Bone.040')
    bone.head = -3.4136, -2.0196, -0.0147
    bone.tail = -3.4177, -2.7908, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.039']]
    bone.bbone_segments = 5
    bones['Bone.040'] = bone.name
    bone = arm.edit_bones.new('Bone.042')
    bone.head = -3.7576, -1.9469, -0.0147
    bone.tail = -3.7611, -2.6045, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.041']]
    bone.bbone_segments = 5
    bones['Bone.042'] = bone.name
    bone = arm.edit_bones.new('Bone.031')
    bone.head = -4.9128, -1.1414, -0.0147
    bone.tail = -4.9147, -1.4970, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.029']]
    bone.bbone_segments = 5
    bones['Bone.031'] = bone.name
    bone = arm.edit_bones.new('Bone.033')
    bone.head = -5.2355, -1.1233, -0.0147
    bone.tail = -5.2369, -1.3874, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.030']]
    bone.bbone_segments = 5
    bones['Bone.033'] = bone.name
    bone = arm.edit_bones.new('Bone.036')
    bone.head = -4.1607, -1.7915, -0.0147
    bone.tail = -4.1638, -2.3751, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.035']]
    bone.bbone_segments = 5
    bones['Bone.036'] = bone.name
    bone = arm.edit_bones.new('Bone.038')
    bone.head = -4.5560, -1.6344, -0.0147
    bone.tail = -4.5584, -2.0954, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.037']]
    bone.bbone_segments = 5
    bones['Bone.038'] = bone.name
    bone = arm.edit_bones.new('Bone.032')
    bone.head = -4.9147, -1.4970, -0.0147
    bone.tail = -4.9166, -1.8525, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.031']]
    bone.bbone_segments = 5
    bones['Bone.032'] = bone.name
    bone = arm.edit_bones.new('Bone.034')
    bone.head = -5.2369, -1.3874, -0.0147
    bone.tail = -5.2383, -1.6514, -0.0147
    bone.roll = -1.5649
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bone.033']]
    bone.bbone_segments = 5
    bones['Bone.034'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Bone.083']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone']]
    pbone.rigify_type = 'limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.006']]
    pbone.rigify_type = 'vizor.limbs.feathers'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.005']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'circle'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.007']]
    pbone.rigify_type = 'vizor.limbs.feathers'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.020']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.021']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.022']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.023']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.024']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.003']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'circle'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.009']]
    pbone.rigify_type = 'vizor.limbs.feathers'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.008']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.016']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.017']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.018']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.019']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.053']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.055']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.057']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.059']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.061']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.004']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.010']]
    pbone.rigify_type = 'vizor.limbs.feathers'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'circle'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.025']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.026']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.043']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.045']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.047']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.049']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.051']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.054']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.056']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.058']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.060']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.062']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.011']]
    pbone.rigify_type = 'vizor.limbs.feathers'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'arm')
    pbone = obj.pose.bones[bones['Bone.027']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.028']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.039']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.041']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.044']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.046']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.048']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.050']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.052']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.029']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bone.030']]
    pbone.rigify_type = 'limbs.simple_tentacle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    try:
        pbone.rigify_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'feathers (tweaks)')
    pbone = obj.pose.bones[bones['Bone.035']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.037']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.040']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.042']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.031']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.033']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.036']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.038']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.032']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')
    pbone = obj.pose.bones[bones['Bone.034']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'feathers')

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
