import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(6):
        arm.rigify_colors.add()

    arm.rigify_colors[0].name = "Root"
    arm.rigify_colors[0].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[0].normal = Color((0.4353, 0.1843, 0.4157))
    arm.rigify_colors[0].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[0].standard_colors_lock = True
    arm.rigify_colors[1].name = "IK"
    arm.rigify_colors[1].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[1].normal = Color((0.6039, 0.0000, 0.0000))
    arm.rigify_colors[1].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[1].standard_colors_lock = True
    arm.rigify_colors[2].name = "Special"
    arm.rigify_colors[2].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[2].normal = Color((0.9569, 0.7882, 0.0471))
    arm.rigify_colors[2].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[2].standard_colors_lock = True
    arm.rigify_colors[3].name = "Tweak"
    arm.rigify_colors[3].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[3].normal = Color((0.0392, 0.2118, 0.5804))
    arm.rigify_colors[3].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[3].standard_colors_lock = True
    arm.rigify_colors[4].name = "FK"
    arm.rigify_colors[4].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[4].normal = Color((0.1176, 0.5686, 0.0353))
    arm.rigify_colors[4].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[4].standard_colors_lock = True
    arm.rigify_colors[5].name = "Extra"
    arm.rigify_colors[5].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[5].normal = Color((0.9686, 0.2510, 0.0941))
    arm.rigify_colors[5].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[5].standard_colors_lock = True

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Face', ui_row=1, color_set_id=6)
    add_bone_collection('Face (Tweak)', ui_row=2, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Spine', ui_row=4, color_set_id=3)
    add_bone_collection('Spine (Tweak)', ui_row=5, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Wing.L (IK)', ui_row=7, color_set_id=5)
    add_bone_collection('Wing.L (FK)', ui_row=9)
    add_bone_collection('Wing.L (Tweak)', ui_row=8, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Wing.R (IK)', ui_row=7, color_set_id=5)
    add_bone_collection('Wing.R (FK)', ui_row=9)
    add_bone_collection('Wing.R (Tweak)', ui_row=8, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Leg.L (IK)', ui_row=14, color_set_id=2)
    add_bone_collection('Leg.L (FK)', ui_row=15, color_set_id=5)
    add_bone_collection('Leg.L (Tweak)', ui_row=16, color_set_id=4)
    add_bone_collection('Leg.R (IK)', ui_row=14, color_set_id=2)
    add_bone_collection('Leg.R (FK)', ui_row=15, color_set_id=5)
    add_bone_collection('Leg.R (Tweak)', ui_row=16, color_set_id=4)
    add_bone_collection('Claws.L', ui_row=17, color_set_id=6)
    add_bone_collection('Claws.L (Tweak)', ui_row=18, color_set_id=4)
    add_bone_collection('Claws.R', ui_row=17)
    add_bone_collection('Claws.R (Tweak)', ui_row=18)
    add_bone_collection('Feathers.L', ui_row=10)
    add_bone_collection('Feathers.L (Tweak)', ui_row=11, color_set_id=6)
    add_bone_collection('Feathers.R', ui_row=10)
    add_bone_collection('Feathers.R (Tweak)', ui_row=11)
    add_bone_collection('Tail', ui_row=12)
    add_bone_collection('Root', ui_row=21, color_set_id=1)

    bones = {}

    bone = arm.edit_bones.new('shoulder.L')
    bone.head = 0.0025, -0.1880, 0.4070
    bone.tail = 0.0910, -0.1587, 0.4303
    bone.roll = 2.0122
    bone.use_connect = False
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('w_body_feather.L')
    bone.head = 0.0334, -0.1261, 0.4696
    bone.tail = 0.0477, -0.0102, 0.4728
    bone.roll = 3.0543
    bone.use_connect = False
    bone.bbone_segments = 5
    bones['w_body_feather.L'] = bone.name
    bone = arm.edit_bones.new('w_body_feather.002.L')
    bone.head = 0.0442, -0.1268, 0.4770
    bone.tail = 0.0653, -0.0509, 0.4686
    bone.roll = 3.0648
    bone.use_connect = False
    bone.bbone_segments = 5
    bones['w_body_feather.002.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head = 0.0977, -0.1436, 0.4413
    bone.tail = 0.2727, -0.0752, 0.4515
    bone.roll = 2.7963
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('w_shoulder_feather.L')
    bone.head = 0.0624, -0.2149, 0.4453
    bone.tail = 0.0599, -0.1490, 0.4628
    bone.roll = 2.9470
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bone.bbone_segments = 5
    bones['w_shoulder_feather.L'] = bone.name
    bone = arm.edit_bones.new('w_body_feather.001.L')
    bone.head = 0.0477, -0.0102, 0.4728
    bone.tail = 0.0535, 0.0368, 0.4741
    bone.roll = 3.0543
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_body_feather.L']]
    bone.bbone_segments = 5
    bones['w_body_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('w_body_feather.003.L')
    bone.head = 0.0653, -0.0509, 0.4686
    bone.tail = 0.1066, 0.0973, 0.4522
    bone.roll = 3.0648
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_body_feather.002.L']]
    bone.bbone_segments = 5
    bones['w_body_feather.003.L'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head = 0.2727, -0.0752, 0.4515
    bone.tail = 0.5110, -0.1581, 0.4000
    bone.roll = 3.1341
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.L')
    bone.head = 0.2374, -0.0774, 0.4558
    bone.tail = 0.2450, -0.0188, 0.4432
    bone.roll = 3.1208
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.003.L')
    bone.head = 0.1548, -0.1113, 0.4468
    bone.tail = 0.1662, -0.0497, 0.4453
    bone.roll = 3.0638
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.003.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.006.L')
    bone.head = 0.0995, -0.1185, 0.4494
    bone.tail = 0.1159, -0.0488, 0.4473
    bone.roll = 3.0560
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.006.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.009.L')
    bone.head = 0.1141, -0.2182, 0.4337
    bone.tail = 0.1569, -0.1605, 0.4574
    bone.roll = 3.0899
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.009.L'] = bone.name
    bone = arm.edit_bones.new('w_shoulder_feather.001.L')
    bone.head = 0.0599, -0.1490, 0.4628
    bone.tail = 0.0575, -0.0832, 0.4803
    bone.roll = 2.9470
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_shoulder_feather.L']]
    bone.bbone_segments = 5
    bones['w_shoulder_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('w_body_feather.004.L')
    bone.head = 0.1066, 0.0973, 0.4522
    bone.tail = 0.1287, 0.1768, 0.4434
    bone.roll = 3.0648
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_body_feather.003.L']]
    bone.bbone_segments = 5
    bones['w_body_feather.004.L'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head = 0.5110, -0.1581, 0.4000
    bone.tail = 0.6986, -0.1442, 0.3561
    bone.roll = 3.0265
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.L')
    bone.head = 0.3079, -0.0721, 0.4494
    bone.tail = 0.3142, -0.0137, 0.4376
    bone.roll = -2.9776
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.003.L')
    bone.head = 0.3772, -0.1052, 0.4424
    bone.tail = 0.3834, -0.0405, 0.4279
    bone.roll = -2.9178
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.003.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.006.L')
    bone.head = 0.4425, -0.1287, 0.4195
    bone.tail = 0.4502, -0.0607, 0.4037
    bone.roll = -2.7814
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.006.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.009.L')
    bone.head = 0.5013, -0.1485, 0.4018
    bone.tail = 0.5039, -0.0761, 0.3850
    bone.roll = -3.0739
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.009.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.001.L')
    bone.head = 0.2450, -0.0188, 0.4432
    bone.tail = 0.2596, 0.0942, 0.4189
    bone.roll = 3.1208
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.004.L')
    bone.head = 0.1662, -0.0497, 0.4453
    bone.tail = 0.1914, 0.0867, 0.4418
    bone.roll = 3.0638
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.003.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.004.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.007.L')
    bone.head = 0.1159, -0.0488, 0.4473
    bone.tail = 0.1475, 0.0852, 0.4432
    bone.roll = 3.0560
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.006.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.007.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.010.L')
    bone.head = 0.1569, -0.1605, 0.4574
    bone.tail = 0.1997, -0.1028, 0.4811
    bone.roll = 3.0899
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.009.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.010.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.L')
    bone.head = 0.5363, -0.1534, 0.3920
    bone.tail = 0.5630, -0.0688, 0.3709
    bone.roll = -3.0812
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.003.L')
    bone.head = 0.6839, -0.1352, 0.3568
    bone.tail = 0.7421, -0.1193, 0.3361
    bone.roll = -2.9746
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.003.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.006.L')
    bone.head = 0.5834, -0.1320, 0.3754
    bone.tail = 0.6405, -0.0552, 0.3479
    bone.roll = -3.0416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.006.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.009.L')
    bone.head = 0.6395, -0.1287, 0.3652
    bone.tail = 0.7161, -0.0666, 0.3347
    bone.roll = -3.0171
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.009.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.012.L')
    bone.head = 0.6696, -0.1327, 0.3593
    bone.tail = 0.7529, -0.0920, 0.3286
    bone.roll = -2.9504
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.012.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.001.L')
    bone.head = 0.3142, -0.0137, 0.4376
    bone.tail = 0.3271, 0.1061, 0.4135
    bone.roll = -2.9776
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.004.L')
    bone.head = 0.3834, -0.0405, 0.4279
    bone.tail = 0.3958, 0.0884, 0.3992
    bone.roll = -2.9178
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.003.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.004.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.007.L')
    bone.head = 0.4502, -0.0607, 0.4037
    bone.tail = 0.4650, 0.0714, 0.3732
    bone.roll = -2.7814
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.006.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.007.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.010.L')
    bone.head = 0.5039, -0.0761, 0.3850
    bone.tail = 0.5089, 0.0645, 0.3522
    bone.roll = -3.0739
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.009.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.010.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.002.L')
    bone.head = 0.2596, 0.0942, 0.4189
    bone.tail = 0.2678, 0.1569, 0.4054
    bone.roll = 3.1208
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.001.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.002.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.005.L')
    bone.head = 0.1914, 0.0867, 0.4418
    bone.tail = 0.2003, 0.1350, 0.4406
    bone.roll = 3.0638
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.004.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.005.L'] = bone.name
    bone = arm.edit_bones.new('w_upper_arm_feather.008.L')
    bone.head = 0.1475, 0.0852, 0.4432
    bone.tail = 0.1652, 0.1603, 0.4409
    bone.roll = 3.0560
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_upper_arm_feather.007.L']]
    bone.bbone_segments = 5
    bones['w_upper_arm_feather.008.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.001.L')
    bone.head = 0.5630, -0.0688, 0.3709
    bone.tail = 0.6135, 0.0912, 0.3311
    bone.roll = -3.0812
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.001.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.004.L')
    bone.head = 0.7421, -0.1193, 0.3361
    bone.tail = 0.8537, -0.0887, 0.2962
    bone.roll = -2.9746
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.003.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.004.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.007.L')
    bone.head = 0.6405, -0.0552, 0.3479
    bone.tail = 0.7569, 0.1015, 0.2919
    bone.roll = -3.0416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.006.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.007.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.010.L')
    bone.head = 0.7161, -0.0666, 0.3347
    bone.tail = 0.8695, 0.0578, 0.2737
    bone.roll = -3.0171
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.009.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.010.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.013.L')
    bone.head = 0.7529, -0.0920, 0.3286
    bone.tail = 0.9247, -0.0082, 0.2655
    bone.roll = -2.9504
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.012.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.013.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.002.L')
    bone.head = 0.3271, 0.1061, 0.4135
    bone.tail = 0.3330, 0.1616, 0.4023
    bone.roll = -2.9776
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.001.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.002.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.005.L')
    bone.head = 0.3958, 0.0884, 0.3992
    bone.tail = 0.4020, 0.1535, 0.3847
    bone.roll = -2.9178
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.004.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.005.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.008.L')
    bone.head = 0.4650, 0.0714, 0.3732
    bone.tail = 0.4731, 0.1434, 0.3565
    bone.roll = -2.7814
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.007.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.008.L'] = bone.name
    bone = arm.edit_bones.new('w_forearm_feather.011.L')
    bone.head = 0.5089, 0.0645, 0.3522
    bone.tail = 0.5116, 0.1412, 0.3344
    bone.roll = -3.0739
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_forearm_feather.010.L']]
    bone.bbone_segments = 5
    bones['w_forearm_feather.011.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.002.L')
    bone.head = 0.6135, 0.0912, 0.3311
    bone.tail = 0.6431, 0.1851, 0.3077
    bone.roll = -3.0812
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.001.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.002.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.005.L')
    bone.head = 0.8537, -0.0887, 0.2962
    bone.tail = 0.9169, -0.0714, 0.2737
    bone.roll = -2.9746
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.004.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.005.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.008.L')
    bone.head = 0.7569, 0.1015, 0.2919
    bone.tail = 0.8115, 0.1751, 0.2655
    bone.roll = -3.0416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.007.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.008.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.011.L')
    bone.head = 0.8695, 0.0578, 0.2737
    bone.tail = 0.9457, 0.1195, 0.2433
    bone.roll = -3.0171
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.010.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.011.L'] = bone.name
    bone = arm.edit_bones.new('w_hand_feather.014.L')
    bone.head = 0.9247, -0.0082, 0.2655
    bone.tail = 1.0030, 0.0301, 0.2367
    bone.roll = -2.9504
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['w_hand_feather.013.L']]
    bone.bbone_segments = 5
    bones['w_hand_feather.014.L'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Spine')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_body_feather.L']]
    pbone.rigify_type = 'basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_body_feather.002.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.rigify_type = 'limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Wing.L (IK)')
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Wing.L (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Wing.L (FK)')
    pbone = obj.pose.bones[bones['w_shoulder_feather.L']]
    pbone.rigify_type = 'basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_body_feather.001.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_body_feather.003.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Wing.L (IK)')
    pbone = obj.pose.bones[bones['w_upper_arm_feather.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_upper_arm_feather.003.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_upper_arm_feather.006.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_upper_arm_feather.009.L']]
    pbone.rigify_type = 'basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_shoulder_feather.001.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_body_feather.004.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Wing.L (IK)')
    pbone = obj.pose.bones[bones['w_forearm_feather.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.003.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.006.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.009.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_upper_arm_feather.001.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_upper_arm_feather.004.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_upper_arm_feather.007.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_upper_arm_feather.010.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_hand_feather.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.003.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.006.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.009.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.012.L']]
    pbone.rigify_type = 'vizor.basic.my_copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controls = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deforms = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.001.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_forearm_feather.004.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_forearm_feather.007.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_forearm_feather.010.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_upper_arm_feather.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_upper_arm_feather.005.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_upper_arm_feather.008.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.001.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_hand_feather.004.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_hand_feather.007.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_hand_feather.010.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_hand_feather.013.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    pbone = obj.pose.bones[bones['w_forearm_feather.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.005.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.008.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_forearm_feather.011.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.005.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.008.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.011.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['w_hand_feather.014.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Feathers.L (Tweak)')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'bone'
    except AttributeError:
        pass

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
